[theme]
# Primary accent color for interactive elements.
primaryColor = "1E90FF"

# Background color for the main content area.
backgroundColor = "#ffffff"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#ff4b44"

# Color used for almost all text.
textColor = "#05004e"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"