[theme]
# Primary accent color for interactive elements.
primaryColor = "#455d7a"

# Background color for the main content area.
backgroundColor = "#e3e3e3"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#f76b8a"

# Color used for almost all text.
textColor = "#680747"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"